setup.cfg: Convert to ASCII
Before this change, Jenkins Docker agents, for instance 'docker2' failed
on the 'lint' and 'code checks' stages, in mysterious ways.

When the 'lint' stage failed, the following exception was raised when
reading from file, at some point before actual linting began:

  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position
  223: ordinal not in range(128)

When the 'code checks' stage failed, flake8 complained about line
lengths > 79 characters, which was weird since setup.cfg declared the
maximum line length should be 120 characters.

Finally, it turned out that setup.cfg was saved in a non-ASCII encoding,
which apparently messed up some Jenkins agents, but not others.

This change converts the file to ASCII, hopefully fixing the failures.

Change-Id: I184f3cc9624b0c412eced6271f42f56c92e5d29c